name: Prison
version: '${project.version}'
main: me.tox1que.prison.Prison
api-version: '1.19'
depend:
  - JARVIS
  - CMI
  - Vault
  - HeadDatabase
commands:
  test:
    description: Testovací příkaz
  prestige:
    description: Příkaz na vylepšení prestiže
  levelup:
    description: Příkaz na zvýšení úrovně